color:
  saturation: 0.4442153
  brandStrength: 0.9173726
  rhythmicContrast: 0.7873135
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.838153
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1585821
typography_spectrum: 0.4244403
name: 'Dude, I Hear Ya!'
